language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_webapp_db
node_js:
        - "8.9.4"

before_script:

  - psql -c 'create database waiter_webapp_db;' -U postgres
  - psql -U postgres -d waiter_webapp_db -a -f waiter.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2